### ISSUE TITLE
new attribute is required (cornerRound)

### ISSUE THREAD

**Issue by ghost** [SLIBIO/SLib#10]
Among View attributes, it'll be better to define `cornerRound` to specify round size at corners.
It will be useful to create round buttons.

In this case, there will be conflict between `boundShape` attribute.
`boundShape` can be one of `rectangle`, `ellipse`or `roundRect`.
My request is related to `roundRect` but more edge-case.

So I suggest following forms of solution based on removing `boundShape`.
```xml
<View
   ...
   width="dimenWidth"
   height="dimenHeight"
   cornerRound="dimenCorner"
   ...
/>
```
Let's assume that dimenWidth > dimenHeight.
- if dimenCorner=0, same result of `boundShape`=`rectangle`.
- if dimenCorner<dimenHeight/2,  similar to `boundShape`=`roundRect` but more accurate.
- if dimenHeight/2<=dimenCorner<dimenWidth/2, round sides but linear top/bottom lines.
- otherwise, same result of `boundShape`=`ellipse`.

**Comment by fred1218zh** [comment]
SLib.io already has the boundShapeRadius property in View. But I think your suggestion about automatically setting boundShape regarding to the radius is good idea.
