### ISSUE TITLE
UI: values need to be predefined in xml

### ISSUE THREAD

**Issue by ghost** [SLIBIO/SLib#11]
```xml
<image
    name='img1'
    src='@drawable/ui_img1'
    scale='contain'
    width='40%sw'
    height='40%sh'
    centerHorizontal='true'
    top='15%sh'
/>
...
<image
    name='img2'
    src='@drawable/ui_img2'
    scale='contain'
    width='40%sw'
    height='40%sh'
    centerHorizontal='true'
    top='15%sh'
/>
```

Here, it's not convenient to write **40%sp** every time and will be more annoying for update/revision.
Such problems happen in working with values like
- dimension
- color
- number
- animation
- shape

There's already **string** value implemented in desirable way.

**Comment by ghost** [comment]
I've noticed a fatal problem in defining values, i.e. currently **string** value.
Now, if a string value named `app_name` is defined in **sapp.xml**, the value (`app_name`) can't be shared via all screen xml files, e.g. **SplashScreen.xml** and vise-versa.
Each screen xml should use only the values defined inside the file itself. Right?
This is not convenient.

I think all defined values should be shared along with all xml files.
Also, it will be better to be able to gather such values in each specialized file, e.g. strings.xml, dimens.xml, ...
**Update: ** Because some values will be used in several screens and some others are to be used in one screen alone.
I suggest that `Slib` supports `gathering` & `specializing` both to define values.

**Comment by fred1218zh** [comment]
In recent version of `sapp`, there were many fixes regarding constant definitions.
