### ISSUE TITLE
under dev still?

### ISSUE THREAD

**Issue by sunwangme** [SLIBIO/SLib#18]
so long no update

**Comment by fred1218zh** [comment]
Hello,

Thanks for your attention to our project.
We are preparing important core updates including many commits.
I'm going to push them to GitHub from our own git repository when we are 
ready a stable build.
The updates will be public after some days.

Thanks again,

Fred Zhang <fred1218zh@outlook.com>
SLib Team

**Comment by sunwangme** [comment]
good news

**Comment by sunwangme** [comment]
we will write unittests for core
