### ISSUE TITLE
Production use

### ISSUE THREAD

**Issue by bilsou** [SLIBIO/SLib#19]
Has SLib been used in production ? If yes, for which platform and in which context ?

B.

**Comment by bilsou** [comment]
Anyone ?

**Comment by fred1218zh** [comment]
It has been used for several solutions. For example
- Satellite Imagery Application (macOS/Win32/Android/iOS)
Renders 3D representation of Earth based on satellite imagery with custom overlays and objects. SLib's cross-platform rendering modules are used for rendering Earth 3d tiles (surface/depth/overlay/object).  
- Workplace Internet Gateway Solution (Linux)
* Support LAN connection between serveral offices at different cities using P2P connections
* Censors all internet connections and blocks configured IP Addresses and Domains
- P2P Messaging Service (Linux/Win32)
- Some mobile apps games (iOS/Android/Tizen)
...

**Comment by bilsou** [comment]
Thank you for your reply, much appreciated.
