### ISSUE TITLE
Example for iOS and Android

### ISSUE THREAD

**Issue by bilsou** [SLIBIO/SLib#20]
Would it be possible to have any example on how to use SLib for iOS/Android via a tableview/list sample app ?

**Comment by bilsou** [comment]
If possible, at the very least, I would just like to see how an iOS xcodeproj would look like using this app, I can't even find any link for some documentation which is quite problematic to say the least...

**Comment by bilsou** [comment]
anyone ?

**Comment by fred1218zh** [comment]
Slib is moving to new version with massive core update.
iOS example will be added by next week.

**Comment by bilsou** [comment]
Great, will be waiting for it next week then.
Thank you.

**Comment by grossingdev** [comment]
new example is added
`examples/UI/CameraView`
