### ISSUE TITLE
webview is error

### ISSUE THREAD

**Issue by rareli** [SLIBIO/SLib#22]
the webview  is null when open a url/page.
code:

    m_webView = new WebView();
    m_webView->setWidthFilling();
    m_webView->setHeightFilling();
    
    m_webView->loadURL("http://mozilla.org/MPL/2.0/");
    
    Console::println("Error:%s",m_webView->getErrorMessage());
    
    addViewToContent(m_webView);

**Comment by fred1218zh** [comment]
Please check following article.

https://stackoverflow.com/questions/31491187/webview-not-showing-loaded-content

**Comment by fred1218zh** [comment]
You can add following lines to `info.plist` in your project.
```
<key>NSAppTransportSecurity</key>
<dict>
  <key>NSAllowsArbitraryLoads</key>
      <true/>
</dict>
```

**Comment by rareli** [comment]
OK,good job！
