### ISSUE TITLE
How to create a new project in SLIBIO.

### ISSUE THREAD

**Issue by rareli** [SLIBIO/SLib#24]
How to create a new project in SLIBIO.
Thanks.

**Comment by fred1218zh** [comment]
You can create a generic project using Xcode (Cocoa) or Visual Studio (Win32), ...
And then, follow the steps in https://github.com/SLIBIO/SLib#integrating-slib-with-existing-c-projects

After this, you can create `app.h`, `app.cpp`, and then update `main.mm` (`main.cpp`)
For this time, you can get code snippets from example projects.

I'm also planning to provide `create-project` bash tool in next release.

**Comment by rareli** [comment]
Look forward to your create-project BASH/CMD/GUI tool.
Thanks.
