### ISSUE TITLE
How to make layout for UI.

### ISSUE THREAD

**Issue by rareli** [SLIBIO/SLib#25]
Like layout in QT:
- QHBoxLayout；
- QVBoxLayout；
- QGridLayout；
- QFormLayout;

**Comment by fred1218zh** [comment]
SLib supports `LinearView` and `ViewGroup` for making layouts. It is similar with Android's `LinearLayout` and `RelativeLayout`.
However, now I'm working on layout related updates and will add new component: `TableView`

**Comment by rareli** [comment]
How to switching a page in UI?

**Comment by fred1218zh** [comment]
```
  openPage(new LoginPage);
```
