### ISSUE TITLE
How to make background's alpha?

### ISSUE THREAD

**Issue by rareli** [SLIBIO/SLib#26]
now,I can't set background's alpha by setAlpha();
eg. 
    m_view = new View;
    m_view->setWidthFilling();
    m_view->setHeight(150);//It's px? I advise to use dp.
    m_view->setTop(0);
    m_view->setBorderColor(slib::Color::Red); // test Color
    m_view->setBorderWidth(2);
    //m_view->setAlwaysOnDrawBackground(true);
    m_view->setBackgroundColor(slib::Color::Blue);
    m_view->setAlpha(0.8);

**Comment by fred1218zh** [comment]
```
m_view->setAlpha(0.8)
```
This will set the alpha of the view object.

To set the background window's alpha, use following snippet
```
getMainWindow()->setAlpha(0.8);
```

**Comment by rareli** [comment]
Yes,I want to set alpha of the view object.
But it seems to be ineffective.

**Comment by fred1218zh** [comment]
You can confirm the effect by setting the background color of the container.

```
getPager()->setBackgroundColor(slib::Color::Black);
```

**Comment by rareli** [comment]
I want to set area of title bar's alpha only,not all pager.
thanks.

**Comment by rareli** [comment]
It's OK:
    
    slib::Color m_color;
    m_color.setRGBA(100, 100, 100, 100);//use Color Object to set alpha.
    m_view->setBackgroundColor(m_color);//OK,It's alpha.

**Comment by fred1218zh** [comment]
m_view->setBackgroundColor(slib::Color(100, 100, 100, 100));

**Comment by rareli** [comment]
Thanks.
