### ISSUE TITLE
How to use dp like android in setWidth/setHeight...?

### ISSUE THREAD

**Issue by rareli** [SLIBIO/SLib#27]
How to use dp(not px) like android in setWidth/setHeight...?

**Comment by fred1218zh** [comment]
Now, SLib only support pixel unit, and have to multiply the dp factor.

**Comment by rareli** [comment]
Now,you can add a function to set dp factor.
and,SLIBIO can auto to multiply the dp factor in some functions.

**Comment by fred1218zh** [comment]
dp is supported via `sapp`
