### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [SLIBIO/SLib#3]
I would like to point out that identifiers like “[`_Brush`](https://github.com/SLIBIO/SLib/blob/c3a35fd5aa1eeb81b3c3c8273825b4d81ba745e1/src/slib/graphics/brush_gdiplus.cpp#L52 "Update candidate")” and “[`_Font`](https://github.com/SLIBIO/SLib/blob/c3a35fd5aa1eeb81b3c3c8273825b4d81ba745e1/src/slib/graphics/font_win32.cpp#L210 "Another update candidate")” [do not fit](https://www.securecoding.cert.org/confluence/display/cplusplus/DCL51-CPP.+Do+not+declare+or+define+a+reserved+identifier "Do not declare an identifier which is reserved for the compiler implementation.") to the expected naming convention of the C++ language standard.
Would you like to adjust your selection for unique names?

**Comment by fred1218zh** [comment]
Thanks for your suggestion.

**Comment by fred1218zh** [comment]
This issue is moved to #5

**Comment by fred1218zh** [comment]
Because it is very big codebase, the reserved name issue will be fixed gradually. Instead I've opened new issue #5

**Comment by elfring** [comment]
There are still [more update candidates to consider](https://github.com/SLIBIO/SLib/blob/e90c6a0a27f84758dcb76a6ba64c9af77d72dd23/src/slib/graphics/font_atlas.cpp#L130 "Renaming for more identifiers?").

**Comment by grossingdev** [comment]
I've pushed remaining updates.

**Comment by elfring** [comment]
Thanks for [another source code improvement](https://github.com/SLIBIO/SLib/commit/86f64e136c6fdb82a824b7fb3ec705bcfd010610 "Renaming of several identifiers").
