### ISSUE TITLE
Allocating an object of abstract class type 'slib::MediaPlayer'

### ISSUE THREAD

**Issue by rareli** [SLIBIO/SLib#30]
I try to use:
m_mediaplayer = new MediaPlayer;

then,Xcode show me:"Allocating an object of abstract class type 'slib::MediaPlayer'"

**Comment by rareli** [comment]
and the same time:
m_sensor = new Sensor;
notice a error.
similar MediaPlayer.

**Comment by fred1218zh** [comment]
use `MediaPlayer::create`

**Comment by fred1218zh** [comment]
Sensor::create  (Only supported on mobile devices)

**Comment by rareli** [comment]
CODE:
m_mediaplayer = new MediaPlayer::create(m_mediaplayerparam);

NOTICE:
No type named 'create' in 'slib::MediaPlayer'

**Comment by fred1218zh** [comment]
It is static function, no type

**Comment by rareli** [comment]
A strange way.
I tried. I failed.
help.

How to create a "const MediaPlayerParam& param"?

**Comment by rareli** [comment]
It's OK.Thanks.
