### ISSUE TITLE
How to using the same directory in xcode and android studio by "Image::loadFromFile/loadFromAsset" function.

### ISSUE THREAD

**Issue by rareli** [SLIBIO/SLib#31]
How to using the same directory in xcode and android studio by "Image::loadFromAsset" function.
In eclipse times,I used "linkedResources" in ".project" file.

**Comment by rareli** [comment]
So I suggest add a simple and representative UI project in github.
It is similar with QT's examples project.

**Comment by fred1218zh** [comment]
You can use `Image::loadFromAsset(path)`

In Android, `path` is relative path to asset.
In Xcode(macOS&iOS), `path` is path to `folder reference`.
In Win32, `path` is relative path from the .exe file.

**Comment by rareli** [comment]
It's OK,thanks.
