### ISSUE TITLE
How to add a new font?

### ISSUE THREAD

**Issue by rareli** [SLIBIO/SLib#33]
How to add a new font in slib?

**Comment by fred1218zh** [comment]
For macOS&iOS, please read following article.
https://developer.apple.com/documentation/uikit/text_display_and_fonts/adding_a_custom_font_to_your_app?language=objc

For Android, please add following lines in the activity.
```
protected void onCreate(Bundle savedInstanceState) {
  super.onCreate(savedInstanceState);
  slib.platform.android.ui.UiFont.registerTypeface("robotobold", Typeface.createFromAsset(getAssets(), "robotobold.ttf"));
}
```
