### ISSUE TITLE
Remove unnecessary null pointer checks

### ISSUE THREAD

**Issue by elfring** [SLIBIO/SLib#4]
[An extra null pointer check is not needed in functions](https://isocpp.org/wiki/faq/freestore-mgmt#delete-handles-null "Do I need to check for null before delete p?") like the following.
- [_Gdiplus_BrushObject](https://github.com/SLIBIO/SLib/blob/c3a35fd5aa1eeb81b3c3c8273825b4d81ba745e1/src/slib/graphics/brush_gdiplus.cpp#L43 "Destructor for _Gdiplus_BrushObject")
- [_Win32_FontObject](https://github.com/SLIBIO/SLib/blob/c3a35fd5aa1eeb81b3c3c8273825b4d81ba745e1/src/slib/graphics/font_win32.cpp#L118 "Destructor for _Win32_FontObject")
- [ScopedPtr<T>::release](https://github.com/SLIBIO/SLib/blob/c3a35fd5aa1eeb81b3c3c8273825b4d81ba745e1/inc/slib/core/detail/scoped.h#L35 "ScopedPtr<T>::release function")

**Comment by fred1218zh** [comment]
null pointer check is needed there.

**Comment by elfring** [comment]
Are you aware that [the delete operator implementation will tolerate passed null pointers](http://en.cppreference.com/w/cpp/memory/new/operator_delete "Description for “operator delete”")?

**Comment by fred1218zh** [comment]
I've really missed that info.
This issue is already fixed.
Thanks for your advise. 👍

**Comment by elfring** [comment]
Which commits will contain corresponding changes?

**Comment by fred1218zh** [comment]
It is https://github.com/SLIBIO/SLib/commit/fe92599b596ddced1aee89e39672020d58891ba5
