### ISSUE TITLE
UrlRequest::post error

### ISSUE THREAD

**Issue by rareli** [SLIBIO/SLib#44]
Android:
error info:java.io.FileNotFoundException.

IOS:
It's OK.

**Comment by rareli** [comment]
I/Console: URL:https://abc.com/getUuid
E/Exception: https://abc.com/getUuid
             java.io.FileNotFoundException: https://abc.com/getUuid
                 at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:250)
                 at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getInputStream(DelegatingHttpsURLConnection.java:210)
                 at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java)
                 at slib.platform.android.network.UrlRequest.execute(UrlRequest.java:134)

**Comment by fred1218zh** [comment]
Fixed issue

**Comment by rareli** [comment]
Request to https website.
Error:D/NetworkSecurityConfig: No Network Security Config specified, using platform default
W/IInputConnectionWrapper: finishComposingText on inactive InputConnection

LOG:
Client not ready yet..Waiting for process to come online
Connected to process 6963 on device smartisan-od103-ce88d86d
Capturing and displaying logcat messages from application. This behavior can be disabled in the "Logcat output" section of the "Debugger" settings page.
I/System: Daemon delayGCRequest, sDelayGCRequest=true, delay=false, sPendingGCRequest=false
I/chromium: [INFO:CONSOLE(4)] "Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.", source: file:///android_asset/images/js/jquery-2.1.4.min.js (4)
D/NetworkSecurityConfig: No Network Security Config specified, using platform default
W/IInputConnectionWrapper: finishComposingText on inactive InputConnection
D/INFO: Keyboard is disappeared
I/Activity: Paused
