### ISSUE TITLE
How to set button in vertical layout?

### ISSUE THREAD

**Issue by rareli** [SLIBIO/SLib#45]
For example:
Some words under a icon/image in center of button.

    m_bButton2->setText("Test Title");
    m_bButton2->setMultiLine(true);
    m_bButton2->setMargin(30, 5, 5, 5);
    m_bButton2->setSize(this->dprToPx(150), this->dprToPx(90));
    m_bButton2->setBorder(false);
    m_bButton2->setTextColor(slib::Color(54,142,244,255));
    m_bButton2->setTextAlignment(slib::Alignment::BottomCenter);
    m_bButton2->setIconMargin(10, 10, 10, 0);
    m_bButton2->setIconSize(this->dprToPx(50), this->dprToPx(50));
    m_bButton2->setIconAlignment(slib::Alignment::TopCenter);
    m_bButton2->setIcon(slib::PlatformDrawable::loadFromAsset("images/images/homebg1.png"));

**Comment by fred1218zh** [comment]
You can use `Button::setLayoutOrientation`

**Comment by rareli** [comment]
It's ok,thanks.
