### ISSUE TITLE
DeviceInformation::getDevicePPI() ERROR

### ISSUE THREAD

**Issue by rareli** [SLIBIO/SLib#48]
IOS:OK
Android:Error

Capturing and displaying logcat messages from application. This behavior can be disabled in the "Logcat output" section of the "Debugger" settings page.
I/System: Daemon delayGCRequest, sDelayGCRequest=false, delay=true, sPendingGCRequest=false
I/Console: Width:1080
           PPI:4294967295(Error value)

code:
Console::print("PPI:%d",DeviceInformation::getDevicePPI());

**Comment by fred1218zh** [comment]
You should call this function after the activity is started.

**Comment by fred1218zh** [comment]
4294967295 means -1 and it is fixed to return 0.

**Comment by rareli** [comment]
OK,Thanks.
