### ISSUE TITLE
Follow the C++ standard rules regarding reserved names

### ISSUE THREAD

**Issue by fred1218zh** [SLIBIO/SLib#5]
The C++ Standard, [reserved.names] [ISO/IEC 14882-2014], specifies the following rules regarding reserved names:

- ...
- Each name that contains a double underscore __ or begins with an underscore followed by an uppercase letter is reserved to the implementation for any use.
- Each name that begins with an underscore is reserved to the implementation for use as a name in the global namespace.
- ...

For more information, visit https://www.securecoding.cert.org/confluence/display/cplusplus/DCL51-CPP.+Do+not+declare+or+define+a+reserved+identifier

**Comment by elfring** [comment]
Would you like to [rename affected identifiers](https://stackoverflow.com/questions/228783/what-are-the-rules-about-using-an-underscore-in-a-c-identifier#answer-228797 "What are the rules about using an underscore in a C++ identifier?") on a corresponding topic branch?

**Comment by fred1218zh** [comment]
Yes, I will update all affected identifiers for next release

**Comment by elfring** [comment]
Thanks for your source code adjustments.

Would you like to achieve further improvements also for software components in the directory “thirdparty”?

**Comment by fred1218zh** [comment]
I don't have plan for `thirdparty` directory for now.
Instead, I'm going to update them when the thirdparty library is improved.

**Comment by elfring** [comment]
* Can the development status of the other components you depend on also be questionable?
* How will the source code evolve further then for your own software?

**Comment by fred1218zh** [comment]
I will manage my own source code at high quality.
Regarding `thirdparty` component, I'm forking source code from other repository and should need to remove components if they have serious issues.
