### ISSUE TITLE
How to capture the LoadUrl completion event of imageView?

### ISSUE THREAD

**Issue by rareli** [SLIBIO/SLib#50]
How to capture the LoadUrl completion event of imageView?

**Comment by fred1218zh** [comment]
you can use following snippet.

UrlRequestParam param;
param.onComplete = [this](UrlRequest* request) {
	if (request->isError()) {
		return;
	}
	Memory mem = request->getResponseContent();
	m_viewImage->setSource(Image::loadFromMemory(mem));
});
UrlRequest::send(param);

**Comment by rareli** [comment]
I have to make a public image cache.
The current idea is to get the image through imageView->getSource() after the current event is retrieved and cached.
There are too many pictures in Sapp that need to be processed in this way, so that  every picture needs to be loaded in c++ code in this solution, which is probably not the best solution.
The best solution is to unify all image load events in the same function.
