### ISSUE TITLE
ChromiumView is empty when start the window by sapp.untill resized the window.

### ISSUE THREAD

**Issue by rareli** [SLIBIO/SLib#51]
A bug in ChromiumView on mac.
I was added ChromiumView into linear in sapp.
but webview can not show in window,untill I have been resized the window.

It's normal without sapp(example  project).
[SAPP]

<sapp>
 <layout
  type='window'
  title='Hello'
  width='900'
  height='800'
  centerScreen='true'
  >
  
  <linear name='mainLinear' width="fill" height="fill" alignCenter='true' background='white'>

  </linear>

  </layout>
</sapp>

[CPP]

void MainWindow::onCreate()
{
    Ref<ChromiumView> m_webView;
    this->setResizable(true);
    m_webView = new ChromiumView;
    m_webView->setWidthFilling();
    m_webView->setHeightFilling();
    m_webView->loadURL("https://bing.com");
    mainLinear->addChild(m_webView);
}

**Comment by fred1218zh** [comment]
Fixed at https://github.com/SLIBIO/SLib/commit/51af198ed5dc2d1a709d612ec229ef76f0f67e91
