### ISSUE TITLE
minimumWidth and minimumHeight seem to be out of work in sapp.

### ISSUE THREAD

**Issue by rareli** [SLIBIO/SLib#52]
minimumWidth and minimumHeight seem to be out of work in sapp.

**Comment by rareli** [comment]
But I can use cpp to set it up.

    this->setMinimumWidth(1200);
    this->setMinimumHeight(800);

**Comment by fred1218zh** [comment]
you can use `minWidth`, `minHeight`

**Comment by rareli** [comment]
ok,thanks
